name: porkvision-1.2
channels:
  - conda-forge
dependencies:
  - numpy=2.2.6
  - opencv=4.11.0
  - pandas=2.2.3  
  - python=3.13.3 
  - pytorch=2.7.0
  - roifile=2025.5.10
  - scikit-image=0.25.2
  - scipy=1.15.2
  - segment-anything=1.0.1
  - tabulate=0.9.0
  - ultralytics=8.3.146

