name: porkvision-1.0.0
channels:
  - conda-forge
dependencies:
  - python=3.9
  - ultralytics=8.2.34
  - segment-anything=1.0.1
  - numpy=2.0.2
  - pandas=2.2.3
  - matplotlib=3.9.4
  - scikit-image=0.24.0
  - shapely=2.0.6
  - scipy=1.13.1
  - pytorch=2.5.1
  - roifile
  - tabulate

  - pip
  - pip:
      - opencv-contrib-python