name: yolosam_env
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.9
  - ultralytics
  - segment-anything
  - numpy
  - opencv
  - pandas
  - matplotlib
  - scikit-image
  - shapely
  - scipy

  - pip
  - pip:
      - lsq-ellipse==2.2.1
      - tabulate