name: porkvision-1.0.0
channels:
  - conda-forge
  - bioconda
  - defaults 
dependencies:
  - python=3.9
  - numpy=2.0.0
  - pandas=2.2.3
  - pytorch=2.5.1
  - scikit-image=0.24.0
  - roifile=2025.5.10
  - tabulate=0.9.0
  - opencv=4.11.0
  - scipy=1.15.2
  - pyimagej               
  - jpype1                 
  - openjdk=11
  - bioconda::fiji             
  - pip
  - pip:
    - ultralytics==8.3.68
    - segment-anything=1.0.1
