name: porkvision-1.0.0
channels:
  - conda-forge
dependencies:
  - numpy
  - opencv
  - pandas
  - python
  - pytorch
  - roifile
  - scikit-image
  - scipy
  - segment-anything
  - tabulate
  - ultralytics

